[project]
name = "aicolonysim"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.7.12",
    "openai>=1.100.2",
    "pydantic>=2.11.7",
    "rich>=14.1.0",
    "seaborn>=0.13.2",
]
